import sys
with open('G:\\Antigravity\\leisure_loop_site\\public\\destination-details.php', 'r', encoding='utf-8') as f: content = f.read()

content = content.replace("<span class='char' style='display:inline-block; clip-path: polygon(0 100%, 100% 100%, 100% 100%, 0% 100%); transform: translateY(40px);'>", "<span class='char anim-char'>")
content = content.replace("<section class=\"parable-hero\" style=\"position: relative; width: 100%; height: 100vh; overflow: hidden; background: #87CEEB; z-index: 1;\">", "<section class=\"parable-hero\">")
content = content.replace("class=\"p-layer\" data-depth=\"0.10\" style=\"position: absolute; inset: -5%; width: 110%; height: 110%; object-fit: cover; z-index: 1; pointer-events: none; filter: brightness(0.8);\"", "class=\"p-layer p-layer-hero-media\" data-depth=\"0.10\"")
content = content.replace("<span style=\"font-size: 1.5rem; color: #fff; letter-spacing: 0.3em; text-transform: uppercase; font-weight: 600; display: block; margin-bottom: 1rem; text-shadow: 0 4px 10px rgba(0,0,0,0.5);\">", "<span class=\"hero-tagline-text\">")
content = content.replace("<h1 style=\"font-family: var(--font-serif); font-size: clamp(3.5rem, 12vw, 12rem); line-height: 1; color: #fff; text-shadow: 0 10px 30px rgba(0,0,0,0.5); margin: 0;\">", "<h1 class=\"hero-title-text\">")
content = content.replace("class=\"p-layer\" data-depth=\"0.10\" style=\"position: absolute; inset: -10%; width: 120%; height: 120%; z-index: 5; pointer-events: none; mix-blend-mode: screen; opacity: 0.8;\"", "class=\"p-layer p-layer-valley-clouds\" data-depth=\"0.10\"")
content = content.replace("<div class=\"scroll-indicator cinematic-indicator\" style=\"z-index: 50;\">", "<div class=\"scroll-indicator cinematic-indicator\">")
content = content.replace("<div class=\"fact-item\" style=\"border-bottom:none; border-right:none;\">", "<div class=\"fact-item no-border-bottom-right\">")
content = content.replace("id=\"narrative\" style=\"z-index: 10;\">", "id=\"narrative\" class=\"z-10\">")
content = content.replace("class=\"absolute w-2/3 h-2/3 z-50 cursor-pointer hit-zone\" style=\"top: 0%; left: 0%;\"", "class=\"absolute w-2/3 h-2/3 z-50 cursor-pointer hit-zone top-0 left-0\"")
content = content.replace("class=\"absolute w-2/3 h-2/3 z-40 cursor-pointer hit-zone\" style=\"top: 16.66%; left: 16.66%;\"", "class=\"absolute w-2/3 h-2/3 z-40 cursor-pointer hit-zone top-[16.66%] left-[16.66%]\"")
content = content.replace("class=\"absolute w-2/3 h-2/3 z-30 cursor-pointer hit-zone\" style=\"top: 33.33%; left: 33.33%;\"", "class=\"absolute w-2/3 h-2/3 z-30 cursor-pointer hit-zone top-[33.33%] left-[33.33%]\"")
content = content.replace("tracking-widest\" style=\"text-decoration:none;\">Plan", "tracking-widest no-underline\">Plan")
content = content.replace("animate-pulse\" style=\"animation-delay: 2s\"></div>", "animate-pulse pulse-circle\"></div>")
content = content.replace("<div class=\"space-y-1 mb-4\" style=\"margin-top:1rem;\">", "<div class=\"space-y-1 mb-4 mt-4\">")
content = content.replace("pointer-events-none\" style=\"opacity: 0;\">", "pointer-events-none opacity-0\">")

with open('G:\\Antigravity\\leisure_loop_site\\public\\destination-details.php', 'w', encoding='utf-8') as f: f.write(content)
print('Done!')
